### ISSUE TITLE
Frequent 504s from Metaforecast API

### ISSUE THREAD

**Issue by mqp** [QURIresearch/metaforecast#101]
I'm working on the pipeline that Base Rate Times uses to get its data from Metaforecast, and it's difficult to get reliable responses from the Metaforecast API. For example, [this query](https://metaforecast.org/api/graphql?query=%7Bquestion%28id%3A+%22goodjudgmentopen-2617%22%29+%7Bhistory+%7Boptions+%7Bname+probability%7D+fetchedStr%7D%7D%7D) frequently fails with a 504:
```graphql
{
  question(id: "goodjudgmentopen-2617") {
    history {
      options {
        name
        probability
      }
      fetchedStr
    }
  }
}
```
```json
{
  "error": {
    "code": "504",
    "message": "An error occurred with your deployment"
  }
}
```
When it does work, it's also very slow.

Doing concurrent requests (e.g. for multiple markets at once) seems to make it more likely to timeout and fail.

Making this more reliable would make our lives a lot easier! Appreciate the service.

**Comment by NunoSempere** [comment]
Received. 

Are you also getting problems when just fetching the latest probability? Is there some way you could just fetch the latest probability, rather than the full history every time?

**Comment by NunoSempere** [comment]
E.g., using this query instead is almost instant and should work well:

```
{
  question(id: "goodjudgmentopen-2617") {
      options {
        name
        probability
      }
      fetchedStr
    
  }
}
```

**Comment by mqp** [comment]
Interesting. The reason is because Base Rate Times doesn't have a database of its own, it just runs some scripts to scrape the full history for its charts from Metaforecast every time it wants updated numbers for those charts.

I don't think there's a way in your GraphQL endpoint to query for a timestamp `>` some previous checkpoint, right? So even if we had a database with the existing data, I am not sure we could use this technique to get what we were missing and compile an up-to-date chart.

**Comment by berekuk** [comment]
This looks like a problem with missing DB indexes, I'll try to fix it in a few hours.

**Comment by mqp** [comment]
That makes sense, thank you very much!

**Comment by berekuk** [comment]
Should be much better now!

**Comment by mqp** [comment]
Confirmed that the latency is under control now -- it takes only a few hundred ms for queries of this form for different markets. (By the way, I didn't mention this, but there was a large caching effect before, where running the same query twice would be fast the second time.)

Thanks for the fix!
