### ISSUE TITLE
What is `INSERT INTO latest.frontpage(frontpage_full, frontpage_sliced) VALUES($1, $2)` doing, in `src/backend/frontpage.ts`?

### ISSUE THREAD

**Issue by NunoSempere** [QURIresearch/metaforecast#20]
I don't get what [this line](https://github.com/QURIresearch/metaforecast/blob/master/src/backend/frontpage.ts#L59=) is doing, and the [Postgres documentation](https://www.postgresql.org/docs/9.2/sql-insert.html) isn't much help. 

In particular, I'm confused by inserting two tables into another table. Just pointing me to some documentation on this is fine.

**Comment by berekuk** [comment]
It just adds a new row to the frontpage table. `frontpage_full` and `frontpage_sliced` are not tables, but column names (see [pgInitializeFrontpage code](https://github.com/QURIresearch/metaforecast/blob/1ac56a3ee6a92f35b6465a7373528275279d71cf/src/backend/database/pg-wrapper.js#L312)).

It means that the table will grow indefinitely, but I tried to reproduce the old behavior which kept each version in the log.

Maybe that's excessive, though, and maintaining a single row table with upserts would be enough, what do you think?

**Comment by NunoSempere** [comment]
Thanks, didn't realize that these were json objects. A single row table with upserts does feel like enough.
