### ISSUE TITLE
Is deleting deprecated code ok?

### ISSUE THREAD

**Issue by berekuk** [QURIresearch/metaforecast#22]
I'm continuing my typescript refactorings and some code is too broken to be converted (platforms/deprecated/ stuff) and too dead to care about.

Is it ok if I just remove it from the repo? It can always be brought back from git archives if necessary.

Similar question about backend/utils/misc stuff, most of it seem like one-shot scripts which probably shouldn't be maintained indefinitely. But the intent is not always clear to me. And also flow/history/old.

**Comment by NunoSempere** [comment]
platforms/deprecated and flow/history/old is ok to remove. I'm less certain about backend/utils/misc, and it doesn't make sense to update them. But I still sort of expect to use them for, e.g., updating the database with new givewell/openphil predictions.

**Comment by OAGr** [comment]
Note that you could always get them in the git repo, naturally. From what I've heard, it's generally a good idea to throw away dead code, just make a point to flag where it existed.

**Comment by berekuk** [comment]
Thanks!
