### ISSUE TITLE
Build frontpage table by storing ids only

### ISSUE THREAD

**Issue by berekuk** [QURIresearch/metaforecast#49]
Right now `frontpage` table is filled with huge json fields.

It'd be better to keep a simple table with 50 ids, and then join it with `questions` in `getFrontpage`. I'm pretty sure the performance won't degrade.

(And `frontpage_full` is entirely unnecessary, since the same effect can be achieved with `SELECT * FROM questions`).

PS: This is not really important, but it's part of the work I'd like to do on normalizing the database.

**Comment by NunoSempere** [comment]
> I'm pretty sure the performance won't degrade

No strong opinions, happy to defer to you
