### ISSUE TITLE
Metaforecast was briefly down

### ISSUE THREAD

**Issue by NunoSempere** [QURIresearch/metaforecast#57]
Metaforecast was briefly down, by guess as a result of merging [#53](https://github.com/quantified-uncertainty/metaforecast/pull/53/), perhaps because of the same reason as [this comment](https://github.com/quantified-uncertainty/metaforecast/pull/53/#issuecomment-1097184956=). I restored a previous version on netlify.

**Comment by berekuk** [comment]
Hmm. How exactly down?

I haven't touched Netlify env, I pushed env only to Vercel and Heroku through terraform, but I haven't configured Netlify with terraform, so #15 shouldn't be a problem.

And deploy preview for #53 seems ok.

**Comment by NunoSempere** [comment]
![ssl](https://user-images.githubusercontent.com/16527456/163052709-57924c0d-227a-4b15-9090-9429a682459c.png)

To replicate:
- Go to https://app.netlify.com/sites/metaforecast/deploys and deploy the latest deploy

**Comment by berekuk** [comment]
> Go to https://app.netlify.com/sites/metaforecast/deploys and deploy the latest deploy

Done, works ok. It was probably a bug on Netlify's side.

**Comment by NunoSempere** [comment]
> It was probably a bug on Netlify's side.

Unexpected
