### ISSUE TITLE
Estimated timeline until graphql API?

### ISSUE THREAD

**Issue by NunoSempere** [QURIresearch/metaforecast#59]
Hey @berekuk, someone recently asked for a timeline for the metaforecast graphql API. Thoughts, e.g., as a 90% confidence interval?

**Comment by berekuk** [comment]
I hope to PR & merge something next week (90% that it'll replace most of the existing REST functionality, 80% that it'll replace most of it with some exceptions e.g. Algolia).

I'll also create a draft PR in a few hours and explain there in more detail how everything is going.
