### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by berekuk** [QURIresearch/metaforecast#7]
Can I (gradually) convert everything to Typescript? :)

It seems to me that TS have "won" and everyone converts their projects to it eventually (unless they pick something like ReasonML or Elm).

The costs for converting to TS are proportional to the amount of code, so it might be better to start this early.

I think even with `"noImplicitAny": false` (e.g., most of JS code is a valid TS code) it still might be beneficial for safer refactorings and adopting types gradually.

**Comment by NunoSempere** [comment]
@OAGr, any thoughts? My guess is that this would be fine in itself but might take too much time.

**Comment by OAGr** [comment]
I like Typescript, happy for things to gradually move in that direction.

**Comment by berekuk** [comment]
I added some basic & very forgiving (allowJs=true, strict=false) TypeScript setup in #8.

**Comment by NunoSempere** [comment]
Closing this issue to keep the number of issues contained.
