### ISSUE TITLE
Metaculus community forecasts are flipped

### ISSUE THREAD

**Issue by Platinuman** [QURIresearch/metaforecast#76]
Steps to reproduce:

1. visit https://metaforecast.org/?forecastingPlatforms=metaculus
2. See difference between metaforecast and metaculus

**Comment by berekuk** [comment]
Ohhh. Unfortunate refactoring, thanks for catching this! Will fix soon.
(It's not just metaculus, all binary probabilities got replaced with max(p, 100-p)...)
